name: in_straw_3pick_diff_st_10_24_2024_5_a_label_zed_rgb
device: 0
workers: 8
confidence: 0.25
target_class: 0
image_ext: png

images_dir: /workspace/data/aghri-val/in_straw_3pick_diff_st_10_24_2024_5_a_label/sensor_data/cam_zed_rgb
output_dir: /workspace/agri-human-dataset-benchmark/2d-tracking/reports/runs/detections

models:
  - name: yolo11s2
    source: /workspace/agri-human-dataset-benchmark/2d-detection/reports/benchmarks/ultralytics/runs/agri-human-detection/yolo11s2/weights/best.pt